### ISSUE TITLE
question about the results of Replica

### ISSUE THREAD

**Issue by ZoranGong** [GradientSpaces/LoopSplat#16]
Hi, 
I found the result of MonoGS in your tab. 1 to be very different from its original paper, especially _off 4_. To ensure it, I run MonoGS in _off 4_ to see how it works but I cannot reproduce the value in your tab. 1. Can you tell me how to get it?

**Comment by Zhu-Liyuan** [comment]
We take the number from Tab.2 (sp) in the original paper (https://arxiv.org/abs/2312.06741). 
![image](https://github.com/user-attachments/assets/da7ae140-de68-4f68-b243-b35ac3b48d12).
I don't understand what you meant by "very different from its original paper" because it's the same as the original paper.

**Comment by ZoranGong** [comment]
sorry, my bad. I didn't notice they revised the value in their latest version. I'll try to use the single process they mentioned.

Thanks for your help and quick response

**Comment by EH-HU** [comment]
Thank you for the prompt response. I will close this issue.
